### ISSUE TITLE
Can't save the plugin

### ISSUE THREAD

**Issue by MzeeAlii** [brpaz/ulauncher-lipsum#1]
I'm getting this error:
`Unexpected API error. KeyError: com.github.brpaz.ulauncher-lipsum`
This is one cool plugin. Saves me a tonne of headache. I always have to Google every time I'm coding to get some Lorem Ipsum text.
Please consider fixing this.

**Comment by brpaz** [comment]
I have tried a fresh Install of the plugin and I cant reproduce the error. have you installed the "lorem" package: "pip install lorem"?

**Comment by cecoates** [comment]
I was having this same issue.

I can confirm that once I installed pip:

sudo apt install python-pip

And installed the lorem module:

pip install lorem

Then restarted Ulauncher (important to actually restart to reload the extensions), the error went away.

**Comment by douglascomim** [comment]
'pip install lorem' work for me.
After restart app, not necessary click save in extension.
