### ISSUE TITLE
Keyword is not working

### ISSUE THREAD

**Issue by awmottaz** [brpaz/ulauncher-lipsum#4]
Typing the keyword does not bring up the extension. It instead suggests opening the Logs application. Exiting and restarting ULauncher does not help.

![Screenshot from 2019-12-17 10-53-16](https://user-images.githubusercontent.com/17735385/71016953-7dd05580-20bb-11ea-8d8f-f10bf5e7b564.png)
![Screenshot from 2019-12-17 10-49-28](https://user-images.githubusercontent.com/17735385/71016951-7dd05580-20bb-11ea-915f-7c8d28e51394.png)

**Comment by brpaz** [comment]
The extension is probably not running. Please make sure you have installed all the dependencies specified in the README

**Comment by azhinu** [comment]
Still not working

**Comment by brpaz** [comment]
This is an old issue. I will close it. If you still have problems please check [Ulauncher Extension Doesn´t install and now?<](https://ulauncher-extension-doesnt-install-and-now.netlify.app/) and open a new issue with the extension logs.

Thank you.
